-- =============================================================================
-- dsp_config_pkg.vhd
-- Project-wide DSP Configuration Package
--
-- Single source of truth for all numeric constants used across RTL modules
-- and testbenches.  Change values here; everything else picks them up at
-- elaboration time without touching any other file.
--
-- Usage in VHDL files:
--   library ieee;
--   use ieee.std_logic_1164.all;
--   use ieee.numeric_std.all;
--   use work.dsp_config_pkg.all;
--
-- Standard: IEEE 1076-2008
-- =============================================================================

package dsp_config_pkg is

    -- -------------------------------------------------------------------------
    -- Word width
    -- All modules in the pipeline use the same signed integer width.
    -- -------------------------------------------------------------------------
    constant C_DATA_BITS : integer := 16;

    -- -------------------------------------------------------------------------
    -- FIR low-pass filter
    -- Hamming-windowed sinc, fc = 0.25 * fs, 8 taps.
    -- Coefficients generated by scripts/design_filter.py (single source of truth).
    -- Sum = 256 -> DC gain = 1.0.  Symmetric -> H(Nyquist) = 0 exactly.
    -- -------------------------------------------------------------------------
    constant C_FIR_TAPS  : integer := 8;
    constant C_FIR_SCALE : integer := 8;   -- coefficients scaled by 2^8 = 256

    -- -------------------------------------------------------------------------
    -- Matched filter (FIR correlator)
    -- Template: [0, 50, 150, 250, 100, 0, 0, 0]
    -- Coefficients = time-reversed template (generated by design_matched_filter.py).
    -- Signal energy = sum(T^2) = 97 500.
    -- Expected peak output = 97500 >> C_MF_SCALE = 380 (integer division, perfect match).
    -- -------------------------------------------------------------------------
    constant C_MF_SCALE  : integer := 8;   -- same scaling convention as FIR
    constant C_MF_PEAK   : integer := 380; -- theoretical peak when input = template exactly

    -- -------------------------------------------------------------------------
    -- Threshold detector
    -- Operates on the FIR-filtered signal (signed magnitude, same scale as data).
    -- Fires when |fir_out| > C_THRESHOLD_DET.
    -- 500 is a reasonable midpoint for 16-bit signed data (full-scale = 32767).
    -- -------------------------------------------------------------------------
    constant C_THRESHOLD_DET : integer := 500;

    -- -------------------------------------------------------------------------
    -- Peak detector
    -- Operates on the matched filter output (range 0 .. C_MF_PEAK = 380).
    -- Fires when |mf_out| > C_THRESHOLD_PEAK.
    -- Set to C_MF_PEAK / 2 = 190: half the template peak, giving ~6 dB margin.
    -- -------------------------------------------------------------------------
    constant C_THRESHOLD_PEAK : integer := C_MF_PEAK / 2;  -- 190

    -- -------------------------------------------------------------------------
    -- Peak position counter width
    -- Max detectable window = 2^C_POS_BITS clock cycles.
    -- -------------------------------------------------------------------------
    constant C_POS_BITS : integer := 16;

end package dsp_config_pkg;
