-- =============================================================================
-- fir_filter.vhd
-- 8-Tap FIR Low-Pass Filter (Fixed-Point, 16-bit)
--
-- Architecture:
--   - Shift-register delay line (tap_reg), newest sample at index 0
--   - Multiply-Accumulate (MAC) computed combinatorially via variable,
--     result registered on rising clock edge
--   - Coefficients scaled by 2^SCALE_SHIFT (=256), output divided by same
--     factor → unity DC gain (sum of coefficients = 256)
--   - valid_in / valid_out handshake; output is 1 clock cycle delayed
--
-- Coefficients (Hamming-windowed sinc, fc = 0.25·fs, generated by scripts/design_filter.py):
--   [-1, -6, 25, 110, 110, 25, -6, -1]   (symmetric, sum = 256)
--
-- Ports:
--   clk       : system clock (rising edge active)
--   rst       : synchronous reset, active high
--   data_in   : signed 16-bit input sample
--   valid_in  : '1' when data_in is valid
--   data_out  : signed 16-bit filtered output
--   valid_out : '1' one clock after a valid input
--
-- Standard: IEEE 1076-2008  (compatible with GHDL and Xilinx Vivado)
-- =============================================================================

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity fir_filter is
    port (
        clk       : in  std_logic;
        rst       : in  std_logic;
        data_in   : in  signed(15 downto 0);
        valid_in  : in  std_logic;
        data_out  : out signed(15 downto 0);
        valid_out : out std_logic
    );
end entity fir_filter;

architecture rtl of fir_filter is

    -- Filter parameters
    constant TAPS        : integer := 8;
    constant COEFF_BITS  : integer := 16;
    constant DATA_BITS   : integer := 16;
    constant ACC_BITS    : integer := 40;  -- 16+16 = 32-bit product, 8 taps → 35 bits max; 40 provides margin
    constant SCALE_SHIFT : integer := 8;   -- coefficients × 256; output >> 8 restores unity gain

    -- Low-pass FIR coefficients (symmetric, Hamming window, fc = 0.25·fs)
    -- Generated by scripts/design_filter.py; scaled by 2^8 = 256; sum = 256 -> DC gain = 1.0
    type coeff_array_t is array(0 to TAPS-1) of signed(COEFF_BITS-1 downto 0);
    constant COEFFS : coeff_array_t := (
        to_signed(  -1, COEFF_BITS),   -- h[0]
        to_signed(  -6, COEFF_BITS),   -- h[1]
        to_signed(  25, COEFF_BITS),   -- h[2]
        to_signed( 110, COEFF_BITS),   -- h[3]  (center pair)
        to_signed( 110, COEFF_BITS),   -- h[4]
        to_signed(  25, COEFF_BITS),   -- h[5]
        to_signed(  -6, COEFF_BITS),   -- h[6]
        to_signed(  -1, COEFF_BITS)    -- h[7]
    );

    type tap_array_t is array(0 to TAPS-1) of signed(DATA_BITS-1 downto 0);
    signal tap_reg : tap_array_t := (others => (others => '0'));

begin

    fir_proc : process(clk)
        variable acc     : signed(ACC_BITS-1 downto 0);
        variable tap_vec : tap_array_t;   -- renamed: "taps" == "TAPS" in case-insensitive VHDL
    begin
        if rising_edge(clk) then
            if rst = '1' then
                tap_reg   <= (others => (others => '0'));
                data_out  <= (others => '0');
                valid_out <= '0';
            else
                -- Build current tap vector.
                -- Using a variable ensures data_in is visible in the MAC
                -- computation within the same clock cycle.
                tap_vec(0) := data_in;
                for i in 1 to TAPS-1 loop
                    tap_vec(i) := tap_reg(i-1);
                end loop;

                -- Update shift register (signal; visible from next cycle)
                tap_reg <= tap_vec;

                -- Multiply-Accumulate
                -- Product: signed(15:0) × signed(15:0) → signed(31:0)
                -- resize to ACC_BITS sign-extends before accumulation
                acc := (others => '0');
                for i in 0 to TAPS-1 loop
                    acc := acc + resize(COEFFS(i) * tap_vec(i), ACC_BITS);
                end loop;

                -- Remove coefficient scaling: keep bits [SCALE_SHIFT+15 : SCALE_SHIFT]
                -- = arithmetic right shift by SCALE_SHIFT (truncation towards -inf)
                data_out  <= acc(SCALE_SHIFT + DATA_BITS - 1 downto SCALE_SHIFT);
                valid_out <= valid_in;
            end if;
        end if;
    end process fir_proc;

end architecture rtl;
