-- =============================================================================
-- fir_filter.vhd
-- Generic Fixed-Point FIR Filter
--
-- Generics:
--   TAPS        : number of filter taps (default 8)
--   DATA_BITS   : input/output word width in bits (default 16, signed)
--   SCALE_SHIFT : coefficient scaling exponent; coefficients are multiplied
--                 by 2^SCALE_SHIFT and the output is right-shifted by the
--                 same amount (default 8 → scale = 256)
--
-- The coefficient array COEFFS must have exactly TAPS entries and must be
-- consistent with SCALE_SHIFT.  Use scripts/design_filter.py to generate
-- both the coefficients and the correct SCALE_SHIFT value.
--
-- Architecture:
--   - Shift-register delay line (tap_reg), newest sample at index 0
--   - MAC computed in the same clock cycle via a VHDL variable (tap_vec)
--   - Accumulator width = 2*DATA_BITS + 8 (safe for up to 256 taps)
--   - valid_in / valid_out handshake; latency = 1 clock cycle
--
-- Standard: IEEE 1076-2008  (compatible with GHDL and Xilinx Vivado)
-- =============================================================================

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity fir_filter is
    generic (
        TAPS        : integer := 8;    -- number of filter taps
        DATA_BITS   : integer := 16;   -- input/output word width (signed)
        SCALE_SHIFT : integer := 8     -- coefficient scale = 2^SCALE_SHIFT
    );
    port (
        clk       : in  std_logic;
        rst       : in  std_logic;
        data_in   : in  signed(DATA_BITS-1 downto 0);
        valid_in  : in  std_logic;
        data_out  : out signed(DATA_BITS-1 downto 0);
        valid_out : out std_logic
    );
end entity fir_filter;

architecture rtl of fir_filter is

    -- Accumulator width: each product is 2*DATA_BITS bits wide; +8 bits of headroom
    -- allows safe summation of up to 2^8 = 256 taps without overflow.
    -- Invariant: ACC_BITS = 2*DATA_BITS + 8  >=  2*DATA_BITS + ceil(log2(TAPS)).
    constant ACC_BITS : integer := 2 * DATA_BITS + 8;

    -- Coefficients (Hamming-windowed sinc, fc = 0.25*fs, 8 taps)
    -- Generated by scripts/design_filter.py; scaled by 2^SCALE_SHIFT = 256.
    -- Values shown are scaled integers; actual floating-point = value / 256.
    -- Sum = 256 -> DC gain = 1.0;  symmetric -> H(Nyquist) = 0 exactly.
    --
    -- NOTE: update this array when TAPS or SCALE_SHIFT changes.
    -- Run: python scripts/design_filter.py
    type coeff_array_t is array(0 to TAPS-1) of signed(DATA_BITS-1 downto 0);
    constant COEFFS : coeff_array_t := (
        to_signed(  -1, DATA_BITS),   -- h[0]
        to_signed(  -6, DATA_BITS),   -- h[1]
        to_signed(  25, DATA_BITS),   -- h[2]
        to_signed( 110, DATA_BITS),   -- h[3]  (center pair)
        to_signed( 110, DATA_BITS),   -- h[4]
        to_signed(  25, DATA_BITS),   -- h[5]
        to_signed(  -6, DATA_BITS),   -- h[6]
        to_signed(  -1, DATA_BITS)    -- h[7]
    );

    type tap_array_t is array(0 to TAPS-1) of signed(DATA_BITS-1 downto 0);
    signal tap_reg : tap_array_t := (others => (others => '0'));

begin

    fir_proc : process(clk)
        variable acc     : signed(ACC_BITS-1 downto 0);
        variable tap_vec : tap_array_t;
    begin
        if rising_edge(clk) then
            if rst = '1' then
                tap_reg   <= (others => (others => '0'));
                data_out  <= (others => '0');
                valid_out <= '0';
            else
                -- Build current tap vector.
                -- tap_vec(0) = current input (variable -> visible in MAC this cycle)
                -- tap_vec(1..TAPS-1) = previous samples from shift register
                tap_vec(0) := data_in;
                for i in 1 to TAPS-1 loop
                    tap_vec(i) := tap_reg(i-1);
                end loop;

                -- Update shift register
                tap_reg <= tap_vec;

                -- Multiply-Accumulate
                acc := (others => '0');
                for i in 0 to TAPS-1 loop
                    acc := acc + resize(COEFFS(i) * tap_vec(i), ACC_BITS);
                end loop;

                -- Remove coefficient scaling (arithmetic right-shift)
                data_out  <= acc(SCALE_SHIFT + DATA_BITS - 1 downto SCALE_SHIFT);
                valid_out <= valid_in;
            end if;
        end if;
    end process fir_proc;

end architecture rtl;
