-- =============================================================================
-- matched_filter.vhd
-- Matched Filter (FIR Correlator)
--
-- A matched filter is a FIR filter whose coefficients are the TIME-REVERSED
-- template signal.  When the input contains the template exactly, the filter
-- output is maximised (equals the signal energy >> SCALE_SHIFT).
-- For any other input of equal or lower energy the output is lower, making it
-- the optimal linear detector in white Gaussian noise.
--
-- Template:         [0, 50, 150, 250, 100,   0,   0,   0]
-- MF coefficients:  [0,  0,   0, 100, 250, 150,  50,   0]  (time-reversed)
-- SCALE_SHIFT = 8  ->  output = dot(h, x) >> 8
-- Signal energy     = sum(T^2) = 97 500
-- Expected peak out = 97500 >> 8 = 380  (when input matches template)
-- Suggested threshold: 190  (half of peak)
--
-- Generics:
--   DATA_BITS   : word width (input and output, signed)
--   SCALE_SHIFT : arithmetic right-shift applied to accumulator
--
-- Architecture: identical to fir_filter.vhd; coefficients are fixed.
-- Latency: 1 clock cycle.
-- Standard: IEEE 1076-2008.
-- =============================================================================

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity matched_filter is
    generic (
        DATA_BITS   : integer := 16;
        SCALE_SHIFT : integer := 8
    );
    port (
        clk       : in  std_logic;
        rst       : in  std_logic;
        data_in   : in  signed(DATA_BITS-1 downto 0);
        valid_in  : in  std_logic;
        data_out  : out signed(DATA_BITS-1 downto 0);
        valid_out : out std_logic
    );
end entity matched_filter;

architecture rtl of matched_filter is

    constant TAPS     : integer := 8;
    constant ACC_BITS : integer := 2 * DATA_BITS + 8;

    -- MF coefficients = time-reversed template [0,50,150,250,100,0,0,0]
    -- Generated by scripts/design_matched_filter.py (single source of truth)
    type coeff_array_t is array(0 to TAPS-1) of signed(DATA_BITS-1 downto 0);
    constant COEFFS : coeff_array_t := (
        to_signed(  0, DATA_BITS),   -- h[0]  (template[7] = 0)
        to_signed(  0, DATA_BITS),   -- h[1]  (template[6] = 0)
        to_signed(  0, DATA_BITS),   -- h[2]  (template[5] = 0)
        to_signed(100, DATA_BITS),   -- h[3]  (template[4] = 100)
        to_signed(250, DATA_BITS),   -- h[4]  (template[3] = 250)
        to_signed(150, DATA_BITS),   -- h[5]  (template[2] = 150)
        to_signed( 50, DATA_BITS),   -- h[6]  (template[1] = 50)
        to_signed(  0, DATA_BITS)    -- h[7]  (template[0] = 0)
    );

    type tap_array_t is array(0 to TAPS-1) of signed(DATA_BITS-1 downto 0);
    signal tap_reg : tap_array_t := (others => (others => '0'));

begin

    fir_proc : process(clk)
        variable acc     : signed(ACC_BITS-1 downto 0);
        variable tap_vec : tap_array_t;
    begin
        if rising_edge(clk) then
            if rst = '1' then
                tap_reg   <= (others => (others => '0'));
                data_out  <= (others => '0');
                valid_out <= '0';
            else
                -- Build current tap vector:
                -- tap_vec(0) = current input (variable -> included in MAC this cycle)
                -- tap_vec(1..TAPS-1) = previous samples from shift register
                tap_vec(0) := data_in;
                for i in 1 to TAPS-1 loop
                    tap_vec(i) := tap_reg(i-1);
                end loop;

                -- Update shift register
                tap_reg <= tap_vec;

                -- Multiply-Accumulate
                acc := (others => '0');
                for i in 0 to TAPS-1 loop
                    acc := acc + resize(COEFFS(i) * tap_vec(i), ACC_BITS);
                end loop;

                -- Scale: arithmetic right-shift removes coefficient scaling
                data_out  <= acc(SCALE_SHIFT + DATA_BITS - 1 downto SCALE_SHIFT);
                valid_out <= valid_in;
            end if;
        end if;
    end process fir_proc;

end architecture rtl;
